name: Expo CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  NODE_VERSION: 20
  YARN_VERSION: 1.22.22

  EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"

      - name: Enable Corepack
        run: corepack enable

      - name: Set Yarn Version
        run: corepack prepare yarn@${{ env.YARN_VERSION }} --activate

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Type Check
        run: yarn tsc --noEmit

      - name: Run Tests
        run: yarn test

  build:
    name: EAS Build
    needs: lint-and-test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"

      - name: Enable Corepack
        run: corepack enable

      - name: Set Yarn Version
        run: corepack prepare yarn@${{ env.YARN_VERSION }} --activate

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Build (Preview)
        if: github.ref == 'refs/heads/develop'
        run: eas build --platform all --profile preview
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Build (Production)
        if: github.ref == 'refs/heads/main'
        run: eas build --platform all --profile production
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
